services:
  - type: web
    name: gutenshelf
    runtime: static
    plan: free
    rootDir: ./client
    buildCommand: "bun install && bun run build"
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
