services:
  - type: web
    name: gutenshelf-api
    plan: free
    rootDir: ./server
    buildCommand: "bun install"
    startCommand: "bun src/index.ts"
    healthCheckPath: /

  - type: web
    name: gutenshelf
    runtime: static
    plan: free
    rootDir: ./client
    buildCommand: "bun install && bun run build"
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"