services:
  - type: web
    name: gutenshelf-api
    env: node
    rootDir: ./server
    buildCommand: "bun install"
    startCommand: "bun src/index.ts"
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 20.11.1

  - type: web
    name: gutenshelf
    runtime: static
    rootDir: ./client
    buildCommand: "bun install && bun run build"
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
